# Generated by Django 3.1.7 on 2021-04-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientemodel',
            name='pacienteEstado',
            field=models.BooleanField(default=True),
        ),
    ]
