# Generated by Django 3.1.7 on 2021-04-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_pacientemodel_pacienteestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientemodel',
            name='pacienteEstado',
            field=models.BooleanField(db_column='pac_estado', default=True),
        ),
    ]
