# Generated by Django 3.1.7 on 2021-04-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_auto_20210406_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamientomodel',
            name='tratamientoEstado',
            field=models.BooleanField(db_column='trat_estado', default=True),
        ),
    ]
