# Generated by Django 3.1.7 on 2021-04-07 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_tratamientomodel_tratamientoestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hclinicamodel',
            name='tratamiento',
            field=models.ForeignKey(db_column='tratamiento_id', on_delete=django.db.models.deletion.PROTECT, related_name='hcTratamiento', to='administracion.tratamientomodel'),
        ),
    ]
