# Generated by Django 3.1.7 on 2021-04-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_auto_20210407_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='hclinicamodel',
            name='hclinicaProblema',
            field=models.CharField(db_column='hclinica_problema', help_text='Problema', max_length=50, null=True, verbose_name='Problema'),
        ),
    ]
