# Generated by Django 3.1.7 on 2021-04-07 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_hclinicamodel_hclinicaproblema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hclinicamodel',
            name='paciente',
            field=models.ForeignKey(db_column='paciente_dni', on_delete=django.db.models.deletion.PROTECT, related_name='hcPaciente', to='administracion.pacientemodel'),
        ),
    ]
