# Generated by Django 3.1.7 on 2021-04-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('administracion', '0009_auto_20210407_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('personalId', models.AutoField(db_column='personal_id', primary_key=True, serialize=False, unique=True)),
                ('personalCorreo', models.EmailField(db_column='personal_correo', max_length=50, unique=True, verbose_name='Correo del usuario')),
                ('personalTipo', models.IntegerField(choices=[(1, 'ADMIN'), (2, 'DOCTOR'), (3, 'PACIENTE')], db_column='personal_tipo', verbose_name='Tipo del usuario')),
                ('personalNombre', models.CharField(db_column='personal_nombre', max_length=45, verbose_name='Nombre del Personal')),
                ('personalApellido', models.CharField(db_column='personal_apellido', max_length=45, verbose_name='Apellido del Personal')),
                ('password', models.TextField(db_column='personal_password', verbose_name='Contraseña del usuario')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'personal',
                'verbose_name_plural': 'personales',
                'db_table': 't_personal',
            },
        ),
    ]
