# Generated by Django 3.1.7 on 2021-04-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_auto_20210409_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientemodel',
            name='pacienteImagen',
            field=models.ImageField(db_column='pac_imagen', default='media/platos/default-image.jpg', null=True, upload_to='platos'),
        ),
    ]
