# Generated by Django 3.1.7 on 2021-04-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0017_auto_20210409_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientemodel',
            name='pacienteImagen',
            field=models.ImageField(db_column='pac_imagen', upload_to='pacientes'),
        ),
    ]
