# Generated by Django 3.1.7 on 2021-04-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0020_auto_20210415_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientemodel',
            name='pacienteEstado',
            field=models.BooleanField(db_column='pac_estado', default=True),
        ),
    ]
